repos:
- repo: https://github.com/pycqa/isort
  rev: 5.13.2
  hooks:
    - id: isort
      stages: [commit]

- repo: https://github.com/psf/black
  rev: 24.4.2
  hooks:
    - id: black
      language_version: python3.10.12
      stages: [commit]

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.3.0
  hooks:
    - id: check-yaml
    - id: end-of-file-fixer
    - id: trailing-whitespace

- repo: https://github.com/PyCQA/flake8
  rev: 7.0.0
  hooks:
    - id: flake8
      stages: [commit]

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.10.0
  hooks:
    - id: mypy
      exclude: 'apps/services/migrations'

# - repo: local
#   hooks:
#     - id: pytest
#       name: pytest
#       language: system
#       entry: pytest
#       pass_filenames: false
#       always_run: true
#       stages: [commit]
